# Generated by Django 2.2.5 on 2019-10-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('accessibleGroups', models.CharField(default='none', max_length=100)),
                ('notes', models.CharField(blank=True, default='', max_length=100)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
