# Generated by Django 2.2.5 on 2019-10-30 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tool',
            new_name='myTool',
        ),
    ]
